### ISSUE TITLE
Results change with each running when using multi-threads

### ISSUE THREAD

**Issue by DAyamaCTF** [AlgoLab/bwt-lcp-parallel#1]
I tried this program, but results change with each running when using multi-threads.
The execution environment is as follows:

 - OS: Ubuntu 18.04.2 LTS
 - cpu cores	: 8

I did an experiment for following data (test.fasta) using 8 threads.

Data (test.fasta)
```
>read1
GTCCGTACGTACTGCATGCAGTACTGGTCAGTCAGTCGTACGTACGTCG
```

Command
```
$ ./bwt_lcp test.fasta 8
```

Then, the following BWT strings was output for each execution. (decoded by `./decode_bwt` )
```
GTTTTTCCCCGTTGTTTCAAAAACTTTCCCCAGA$CAGGGGGGGGGGACC
GTTTTTCCCCGTTGTTTCAAAAACTTTCCCCAGA$CAGGGGGGGGGGCAC
```

I think the first one is correct.

**Comment by yp** [comment]
Thanks for reporting this issue. We will look into it as soon as possible.

**Comment by yp** [comment]
You actually uncovered a data race while computing segment boundaries. It should be fixed now. Please let us know if you encounter other issues.
Thanks again.

**Comment by DAyamaCTF** [comment]
It's working as expected.
Thanks.
